# Site Info
title:              "Cookies & Coffee | Theme by Liz Lorena"
description:        "A static jekyll theme by Liz Lorena"
keywords:           "web design, portfolio, blog, jekyll, theme"

#Custom Settings
avatar: "/img/logos/cozymaus-2020-transparent-2.png"
name: "Liz Lorena Berberena"
bio: "Web Designer <br><br> This is my cute lil website theme called Cookies & Coffee. Hope you like it."
#theme: 

# Author Info
author_name:        "Liz Lorena Berberena"
author_email:       liz@lizlorena.com
github_username:    lizberberena
twitter_username:   lorethefour
instagram_username: ""
youtube_username:   ""


# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /posts/:title # Post permalink
timezone:           America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
language:           en-US

# Pagination Settings
paginate_path: "/pg-:num/"
paginate: 5

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: lizlorena

# Site Build
highlighter: rouge
markdown: kramdown
gems:
  - jekyll-sitemap
  - tzinfo
plugins:
  - jekyll-feed
  - jekyll-paginate

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:          "posts"
    values:
      layout:        "post"
